# Site settings
title: Sun Guozheng
email: sdsxsgz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.sunguozheng.com # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

source: .
destination: ./_site



# Build settings
markdown: kramdown

permalink: /:year-:month-:day-:title.html


kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  input: GFM
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: table
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
